/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion.admGrupo;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import linkup.objetosNegocio.admGrupo.Grupo;
import linkup.presentacion.control.admGrupo.ControlAdministrarGrupo;

/**
 *
 * @author gael_
 */
public class frmGruposPrincipal extends javax.swing.JFrame {
    
    public ControlAdministrarGrupo controlador;

    /**
     * Creates new form frmGruposPrincipal
     */
    public frmGruposPrincipal(ControlAdministrarGrupo controlador) {
        this.controlador = controlador;
        initComponents();
        setTitle("Grupos");
        setLocationRelativeTo(null);
        mostrarGrupos();
        tblGrupos.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent evt) {
            int filaSeleccionada = tblGrupos.getSelectedRow();
            if (filaSeleccionada >= 0) {
                String nombreGrupo = tblGrupos.getValueAt(filaSeleccionada, 0).toString();
                Grupo grupoSeleccionado = controlador.obtenerGrupoPorNombre(nombreGrupo);
                if (grupoSeleccionado != null) {
                    controlador.accederGrupo(grupoSeleccionado);
                    dispose(); // opcional, si quieres cerrar esta ventana al entrar
                }
            }
        }
    });
    }
    
    public void mostrarGrupos(){
        List<Grupo> grupos = controlador.obtenerGrupos();
        
        String[] columnas = {"Grupos"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Hacer que todas las celdas no sean editables
            return false;
        }
        };

        for (Grupo grupo : grupos) {
            String nombre = grupo.getNombre();
            modelo.addRow(new Object[]{nombre});
        }

        tblGrupos.setModel(modelo);
        
        Font fuenteGrande = new Font(tblGrupos.getFont().getName(), Font.PLAIN, 18); // Puedes ajustar el tamaño a tu gusto
        tblGrupos.setFont(fuenteGrande);
        tblGrupos.getTableHeader().setFont(fuenteGrande); // También aumentar la fuente del encabezado

        // Aumentar el tamaño de las filas
        tblGrupos.setRowHeight(50); // Puedes ajustar la altura a tu gusto

        // Establecer el color de fondo de la tabla a morado
        tblGrupos.setBackground(Color.WHITE); // Color morado (RGB)
        tblGrupos.setForeground(new Color(102, 0, 102)); // Color del texto en blanco para que contraste

        // Establecer el color de fondo del encabezado a un morado más oscuro (opcional)
        JTableHeader header = tblGrupos.getTableHeader();
        header.setBackground(new Color(102, 0, 102));
        header.setForeground(Color.WHITE);

        // Asegúrate de que el scroll tenga agregada la tabla correctamente
        scrollGrupos.setViewportView(tblGrupos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBlanco = new javax.swing.JPanel();
        PanelRosa = new javax.swing.JPanel();
        PanelLogo = new javax.swing.JLabel();
        PanelMisGrupos = new javax.swing.JLabel();
        btnCrearGrupo = new javax.swing.JButton();
        scrollGrupos = new javax.swing.JScrollPane();
        tblGrupos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(864, 558));

        PanelBlanco.setBackground(new java.awt.Color(255, 255, 255));

        PanelRosa.setBackground(new java.awt.Color(253, 166, 179));
        PanelRosa.setMinimumSize(new java.awt.Dimension(56, 57));
        PanelRosa.setPreferredSize(new java.awt.Dimension(56, 57));
        PanelRosa.setLayout(null);

        PanelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/linklogo.png"))); // NOI18N

        PanelMisGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMisGrupos.png"))); // NOI18N

        btnCrearGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCrearGrupo.png"))); // NOI18N
        btnCrearGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearGrupoActionPerformed(evt);
            }
        });

        scrollGrupos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 63, 75)));

        tblGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollGrupos.setViewportView(tblGrupos);

        javax.swing.GroupLayout PanelBlancoLayout = new javax.swing.GroupLayout(PanelBlanco);
        PanelBlanco.setLayout(PanelBlancoLayout);
        PanelBlancoLayout.setHorizontalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBlancoLayout.createSequentialGroup()
                .addComponent(PanelRosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(scrollGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBlancoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelMisGrupos)
                            .addComponent(PanelLogo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearGrupo)))
                .addGap(60, 60, 60))
        );
        PanelBlancoLayout.setVerticalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLogo)
                .addGap(18, 18, 18)
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearGrupo)
                    .addComponent(PanelMisGrupos))
                .addGap(27, 27, 27)
                .addComponent(scrollGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearGrupoActionPerformed
        controlador.crearGrupo();
        this.dispose();
    }//GEN-LAST:event_btnCrearGrupoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBlanco;
    private javax.swing.JLabel PanelLogo;
    private javax.swing.JLabel PanelMisGrupos;
    private javax.swing.JPanel PanelRosa;
    private javax.swing.JButton btnCrearGrupo;
    private javax.swing.JScrollPane scrollGrupos;
    private javax.swing.JTable tblGrupos;
    // End of variables declaration//GEN-END:variables
}
